### ISSUE TITLE
How to bundle the site locally

### ISSUE THREAD

**Issue by jstify** [DONGChuan/Yummy-Jekyll#1]
Hi,

I have installed all modules, but I got error installing 'nokogiri'.

I am using Ruby 3.0. 

How to build this locally and push site to github?

**Comment by DONGChuan** [comment]
Hi,

Are you on windows or on mac? Do you mind showing me the whole install logs?

And also have a look at the jekyll version you are using. You may could have more than 2 versions in the mean time. I suggest to use 3.0.1 instead of the latest ones.

**Comment by narendrakurapati** [comment]
HI,

I downloaded this and working on the Windows. I have installed:

- ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32] and same devkit
-  gem 2.6.4

I have old installations but i faced problem with Json installation. So I updated to latest one.

I want to check the blog local running. How can I run this locally??

Where do I need to push these file sin git?? Do I need to push in gh-pages of repository or do I need to create a organization for this?

I didn't installed jekyll.

PFA for console log, Please let me know if you need anything.

![jekyll2](https://cloud.githubusercontent.com/assets/3027657/15632828/6ec802c6-25bb-11e6-9fee-1f5fdc7ec882.PNG)
![jekyll3](https://cloud.githubusercontent.com/assets/3027657/15632829/6ecdbbd0-25bb-11e6-9dd2-eed13aa2347c.PNG)
![jekyll](https://cloud.githubusercontent.com/assets/3027657/15632801/c364246e-25ba-11e6-8053-fb2a0c7a725a.PNG)

**Comment by DONGChuan** [comment]
"updated to latest one." So you used the latest jekyll?

To test it on your local, jekyll must be installed -> run "jekyll serve" at the root of the project
To test it directly on your github page. No need gh-page branch or orgnization.
For example, for me, I just created a repo called DONGChuan.github.io

So for you, should be narendrakurapati.github.io. Then update all the files to this repo. Wait 10 seconds (not sure for the first time, how long you need to wait). Then visit http://narendrakurapati.github.io directly. You will see it!

**Comment by DONGChuan** [comment]
Windows is very painful sometimes. Try to install nokogiri by gem directly instead of bundle. To see what will happen.... I did some search: https://gitlab.com/jekyll-themes/default-bundler/wikis/jekyll-with-bundler

It said: Nokogiri is a dependency that might cause errors if it's not added to the script. So if gem install not work, try to add it explicitly in Gemfile.

**Comment by narendrakurapati** [comment]
I have installed latest jekyll (1.8.3).

the gem.lock file has following: 
 nokogiri (1.6.7)
      mini_portile2 (~> 2.0.0.rc2)
 nokogiri (1.6.7-x64-mingw32)
      mini_portile2 (~> 2.0.0.rc2)

This version of nokogiri is not supported in Ruby 2.3.0. I have installed nokogiri 1.6.8 which is supported in Ruby 2.3.0.

Jekyll serve is failed as 'nokogiri 1.6.7' is not found. I want to update 'nokogiri' in gem file as I have 
Ruby 2.3.0
Gem 2.6.4
Bundle 1.12.5

**Comment by DONGChuan** [comment]
Hi Narendrakurapati!

Please update your jekyll. The latest jekyll is now 3.1.3. I suggest you to update Jekyll to **3.0.1**. Because some dependences could not support it yet.

"Jekyll serve is failed as 'nokogiri 1.6.7' is not found. "  + " I have installed nokogiri 1.6.8 "
So please install 1.6.7 instead of 1.6.8.

Try also "gem install" nokogirl 1.6.7. And show the error message :D

**Comment by narendrakurapati** [comment]
HI,

Sorry, I am using Jekyll 3.1.6

I tried to install nokogiri 1.6.7, But This is not support in my Ruby version so that I installed latest one. I want to use this latest verion in the application so I am trying to change gem.lock file.

PFA.

![bundle install](https://cloud.githubusercontent.com/assets/3027657/15644951/77c614c2-2673-11e6-97a9-0c70cb440170.PNG)
![nokogiri](https://cloud.githubusercontent.com/assets/3027657/15644952/77c97e8c-2673-11e6-825c-4aac7ef3591f.PNG)

**Comment by DONGChuan** [comment]
I suggest not use the latest version for the moment.  I got some errors with latest Jekyll. Because not every dependence in Gemfile.lock is compatible with latest Jekyll.

I used Ruby 2.20 on my laptop to use nokogiri 1.6.7 when I did this project. 

I will do some research this weekend on windows to have a check about it.
