### ISSUE TITLE
[Proposal] Remove the comments on the homepage

### ISSUE THREAD

**Issue by LM450N** [DONGChuan/Yummy-Jekyll#27]
I think the comments on the homepage are not really useful. The reason is, these comments will be out of context. Except if you want your visitors criticise your site generally.

<img width="995" alt="capture d ecran 2016-08-31 a 00 16 18" src="https://cloud.githubusercontent.com/assets/2325091/18109331/e6f96534-6f10-11e6-842d-fb13fa5444da.png">

What do you think about it ❓

**Comment by DONGChuan** [comment]
Yeh. My idea firstly is just to have a general view of comments. Maybe we could set an option in _config.yml to turn on/off comments on homepage?

**Comment by matjazmav** [comment]
Not just at homepage but also on any other static page `/about` `/open-source` etc. Add option to page configuration, if option is missing default shoud be "no comments"?

**Comment by ImReallyShiny** [comment]
You could just remove the actual config part in _config and it wont appear - But then it wont appear ANYWHERE

**Comment by DEL-R** [comment]
I already known solution because I've seen it with another template, but while setting up a new Disqus space for a new site I found they now provide [docs for Jekyll setup](https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions) specifically.

[You can make that parameter default for all](https://jekyllrb.com/docs/configuration/#front-matter-defaults) or some layouts and/or disabling it per pages by specifying `false` in the page Front Matter
