### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by jstify** [DONGChuan/Yummy-Jekyll#7]
Hi,

I just forked this theme and changed repository name. It is launched successfully.

I hope it is seems something wrong when compare with [http://dongchuan.github.io/](http://dongchuan.github.io/).

I have hosted at: [https://jstify.github.io/](https://jstify.github.io/)

Note:  I didn't make any changes after fork.

thank you

**Comment by DONGChuan** [comment]
Hi @jstify It is because all the dependencies are missing. If you checked the demo code folder. You will find another folder called "bower_components" in which there are all the dependencies you need. (ex Bootstrap)

In "Install and setup" of the problem, you need to follow the install steps to make sure all the dependencies are downloaded and pushed to your own repos.

![image](https://cloud.githubusercontent.com/assets/2586841/16447169/7ec2ef4a-3deb-11e6-8f10-7b13a2530f3d.png)

**Comment by jstify** [comment]
Okey. Will let you know once I am done with those.

Thank you.

**Comment by jstify** [comment]
Hi,

I have installed all dependencies, but gitignore file as following:

_site
.sass-cache
.jekyll-metadata
.idea
bower_components

which ones I need remove from git ignore to make it work.


thank you

**Comment by DONGChuan** [comment]
just remove bower_components from gitignore :D  My bad

**Comment by jstify** [comment]
Hey,

I am trying add `target: _blank` for navigation items in config.xml then build is failed.

May I know how to add this?

**Comment by LM450N** [comment]
Push the project with all Bower dependencies on GitHub is not really a good practice. Personally, [my site](https://louchart-mason.fr/) is hosted on Firebase which supports SSL (but I pay a domain name). Just to say.

**Comment by jstify** [comment]
How are you handling that then???
